server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.200.131:3306/mytestSerach?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    #配置druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    maxActive: 20
    filters: stat
    maxWait: 60000
    validationQuery: select 'x'
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
      cache: false
  freemarker:
      suffix: .html
      enabled: true
      content-type: text/html
      settings:
        #去掉长数字的逗号
        number_format: 0.##
  jpa:
        show-sql-sql: true
#扫描mabatis文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  spring:
      freemarker:
        allow-request-override: false
        cache: true
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: false
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#打印sql
logging:
  level:
    com.weidijia.psychology.mapper: debug